---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/apps/network/ingress-nginx/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: valinor
  wait: true
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-ingress-nginx-peertube
#   namespace: flux-system
#   labels:
#     substitution.flux.home.arpa/enabled: "true"
# spec:
#   interval: 10m
#   path: "./kubernetes/apps/network/ingress-nginx/peertube"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: valinor
#   wait: true
#   dependsOn:
#     - name: cluster-apps-cert-manager-issuers
