---
# yaml-language-server: $schema=https://ks.hsn.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubernetes-sigs-external-dns
  namespace: flux-system
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/external-dns
  timeout: 3m
