---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - angelnu.yaml
 - authentik.yaml
 - backube.yaml
 - bjw-s.yaml
 - cilium.yaml
 - crowdsec.yaml
 - crunchydata.yaml
 - democratic-csi.yaml
 - descheduler.yaml
 - dragonflydb.yaml
 - elastic.yaml
 - external-secrets.yaml
 - fairwinds.yaml
 - grafana.yaml
 - hetzner.yaml
 - ingress-nginx.yaml
 - intel.yaml
 - jetstack.yaml
 - kubernetes-sigs-external-dns.yaml
 - kubernetes-sigs-metrics-server.yaml
 - kubernetes-sigs-nfd.yaml
 - kyverno.yaml
 - nvidia.yaml
 - openebs.yaml
 - piraeus.yaml
 - postfinance.yaml
 - prometheus-community.yaml
 - rook-ceph.yaml
 - spegel-org.yaml
 - stakater.yaml
 - stevehipwell.yaml
 - victoria-metrics.yaml
