---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nvdp
  namespace: flux-system
spec:
  interval: 30m
  url: https://nvidia.github.io/k8s-device-plugin
  timeout: 3m
