---
# Note: Gatus vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
web:
  port: $${CUSTOM_WEB_PORT}
storage:
  type: postgres
  path: $${DATABASE_URI}
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
alerting:
  pushover:
    application-token: $${CUSTOM_PUSHOVER_TOKEN}
    user-key: $${CUSTOM_PUSHOVER_USER_KEY}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: external
    url: https://status.hsn.dev
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: Nextcloud External
    group: external
    url: https://nc.hsn.dev
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: flux-webhook
    group: external
    url: https://flux-receiver.hsn.dev
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: pushover
  - name: Elessar
    group: internal
    url: https://elessar.jahanson.tech
    interval: 1m
    client:
      dns-resolver: tcp://10.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: Sting
    group: internal
    url: https://sting.jahanson.tech
    interval: 1m
    client:
      dns-resolver: tcp://10.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: Gandalf
    group: internal
    url: icmp://10.1.1.13
    interval: 1m
    client:
      dns-resolver: tcp://10.1.1.1:53
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
  - name: Gollum
    group: internal
    url: http://10.1.1.14
    interval: 1m
    client:
      dns-resolver: tcp://10.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: Nextcloud Internal
    group: internal
    url: https://nc.hsn.dev
    interval: 1m
    client:
      dns-resolver: tcp://10.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: Home Assistant
    group: internal
    url: https://hass.jahanson.tech
    interval: 1m
    client:
      dns-resolver: tcp://10.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
