---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: omegabrr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: omegabrr-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          server:
            host: 0.0.0.0
            port: 80
            apiToken: {{ .OMEGABRR_API_KEY }}
          clients:
            autobrr:
              host: http://autobrr.default.svc.cluster.local
              apikey: {{ .AUTOBRR_API_KEY }}
            arr:
              - name: radarr
                type: radarr
                host: http://radarr.default.svc.cluster.local
                apikey: {{ .radarr_api_key }}
                filters: [2]
              - name: sonarr
                type: sonarr
                host: http://sonarr.default.svc.cluster.local
                apikey: {{ .sonarr_api_key }}
                filters: [1]
                excludeAlternateTitles: true
  dataFrom:
    - extract:
        key: omegabrr
    - extract:
        key: autobrr
    - extract:
        key: radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"
